### ISSUE TITLE
alpine3.7+python3.6.5,expat2.2.6-r0 says 'getrandom: symbol not found', expat2.2.5 works fine

### ISSUE THREAD

**Issue by tianxiawuzhe** [libexpat/libexpat#238]
Using Dockerfile to build image, from alpine:3.7.
> RUN apk add build-base linux-headers python3==3.6.5-r0 ...
then python -m pip install --upgrade --no-cache-dir pip.
Now,  says:
`Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
__import__(pkg_name)
File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 43, in <module>
from pip.utils import get_installed_distributions, get_prog
File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
from pip._vendor import pkg_resources
File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 35, in <module>
import plistlib
File "/usr/lib/python3.6/plistlib.py", line 65, in <module>
from xml.parsers.expat import ParserCreate
File "/usr/lib/python3.6/xml/parsers/expat.py", line 4, in <module>
from pyexpat import *
ImportError: Error relocating /usr/lib/libexpat.so.1: getrandom: symbol not found
`
I tried installing by get-pip.py file, the same error.
To fix this problem, compare the expat's version. Found:
expat2.2.6 not work, expat2.2.5 works fine.
Some bugs for 2.2.6?

**Comment by hartwork** [comment]
That's not a bug in Expat as far as I can tell. If you're sure that what you're trying to do should work out of the box on Alpine, please do a (more) detailed report with Alpine. Thanks!

**Comment by ielepro** [comment]
I also encountered the same problem, and finally found that because of the inconsistent version when modifying the `apk` source, the image I used is alpine3.9, and there is a section in the Dockerfile.
```
RUN echo -e 'http://mirrors.aliyun.com/alpine/v3.8/main/\nhttp://mirrors.aliyun.com/alpine/v3.8/community/' > /etc/apk/repositories
```
After I changed to `v3.9`, everything worked fine.

**Comment by hartwork** [comment]
Thanks for the update!
